### PR TITLE
Right censored lines

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@limnoliver could you pull this down:
```
git checkout -b ldecicco-USGS-master master
git pull git://github.com/ldecicco-USGS/EGRET.git master
```
and see if it looks right with the MMSD data?

**Comment by ldecicco-USGS** [comment]
Finally looked at some MMSD data and it all looks OK in linear scales....got to fix the log

**Comment by ldecicco-USGS** [comment]
image

**Comment by limnoliver** [comment]
Oops, thanks Laura, I somehow missed reviewing this. Will work on testing how the model handles right-censored values as I prep for model runs with MMSD.

**Pull request merged**
